name: CI
on:
    push:
        branches: []
    pull_request:
        branches: ['main', 'develop']
jobs:
    unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: install modules
              run: npm i
            - name: start tests
              run: npm run test
